### ISSUE TITLE
Support 4.1.x

### ISSUE THREAD

**Issue by eric-ooi** [MITRECND/bro-http2#16]
With [Zeek v4.1.1 recently released](https://github.com/zeek/zeek/releases/tag/v4.1.1), it'd be great to get support for the 4.1.x releases.  Submitting this for tracking and to show that there's demand for it. :)

Thanks, @Mraoul!

**Comment by Mraoul** [comment]
I've pushed a new branch called `support-zeek-41` which should support Zeek 4.0 and 4.1. Need to test it a bit more, but this should address all of the changes/deprecations I didn't address in the `support-zeek-40` branch. Assuming no issues, I can merge this one and cut a release.

**Comment by eric-ooi** [comment]
Thanks so much, @Mraoul! I just installed it with no errors and http2.log is showing up again.  You are awesome, thanks again! 🙏

**Comment by eric-ooi** [comment]
Just wanted to say that the newly released Zeek 4.2.x is fully supported with the current release.  Thanks again!
